# Generated by Django 3.0 on 2020-01-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='stroop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=5)),
                ('acertos1', models.IntegerField()),
                ('acertos2', models.IntegerField()),
                ('acertos3', models.IntegerField()),
                ('tempo1', models.CharField(max_length=7)),
                ('tempo2', models.CharField(max_length=7)),
                ('tempo3', models.CharField(max_length=7)),
            ],
        ),
    ]
