# Generated by Django 3.0 on 2020-01-09 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercicios_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=5)),
                ('Vezes_Semana_FC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_FC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_FP', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_FP', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_FS', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_FS', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_HB', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_HB', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_BB', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_BB', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_PS', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_PS', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_ATL', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_ATL', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_NAT', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_NAT', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_GO', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_GO', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_AM', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_AM', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_DAN', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_DAN', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_COR', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_COR', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_BIC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_BIC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_CE', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_CE', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_CT', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_CT', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_VQ', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_VQ', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_VP', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_VP', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_QP', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_QP', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_SB', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_SB', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_MC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_MC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_EF', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_EF', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_TC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_TC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_PC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_PC', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_GA', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_GA', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Vezes_Semana_OA', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='O valor precisa estar entre 0 e 7'), django.core.validators.MaxValueValidator(7, message='O valor precisa estar entre 0 e 7')])),
                ('Minutos_Dia_OA', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message='Por favor, seja realista'), django.core.validators.MaxValueValidator(960, message='Por favor, seja realista')])),
                ('Nao_pratico_AF', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='exercicios',
        ),
    ]
